### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by shenwei356** [shenwei356/csvtk#10]
- [x] `csvtk join` keep source records with same ID. v0.4.5 and later versions support it.
- [x] new command `header`
- [x] new command `head`
- [x] new command `sample`
- [x] new command `csvtk filter2`: support comparison between fields (like `awk '$1 < $4'`) using [govaluate](https://github.com/Knetic/govaluate).
- [x] `csvtk grep`: keep output in order of input
- [x] add alias to stat and stat2
- [x] fix english expression: number fields -> digital
- [ ] add functional tests. too many cases to cover :sob:

**Comment by shenwei356** [comment]
- [ ] add alias to stat and stat2
- [ ] fix english expression: number fields -> deci...
- [ ] add functional tests
