### ISSUE TITLE
TODO: Adding plotting commands

### ISSUE THREAD

**Issue by shenwei356** [shenwei356/csvtk#5]
Including:

- [x] Histogram. `csvtk plot hist`. [example](https://github.com/gonum/plot/wiki/Example-plots#histograms)
- [ ] Bar chart. [example](https://github.com/gonum/plot/wiki/Example-plots#bar-charts)
- [ ] Box plot. [example](https://github.com/gonum/plot/wiki/Example-plots#vertical)
- [ ] line plot

**Comment by shenwei356** [comment]
all done
